In [1]:
# import dependencies
import pandas as pd
import datetime as dt

In [2]:
# attempt to increase col display
pd.set_option('display.max_columns', 28)

In [3]:
# read in csv
policy_df = pd.read_csv('Raw/policy_list.csv')
policy_df.sample(7)

,ID,COUNTRY_NAME,ISO3,ISO2,POLICY_TYPE,POLICY_SUBTYPE,START_DATE,END_DATE,AIR,AIR_TYPE,TARGETS_AIR,LAND,LAND_TYPE,TARGETS_LAND,...,VISA_BAN,VISA_BAN_TYPE,VISA_BAN_LIST,CITIZEN_EXCEP,CITIZEN_EXCEP_LIST,COUNTRY_EXCEP,COUNTRY_EXCEP_LIST,WORK_EXCEP,SOURCE0,SOURCE1,SOURCE2,SOURCE3,SOURCE4,SOURCE5
1138,MG15,"Bonaire, Sint Eustatius and Saba",BES,BQ,PARTIAL,BORDER_CLOSURE,03_27_20,04_16_20,1,Specific,"Austria, Belgium, Bulgaria, Canada, China (Peo...",0,NaN,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20200328232842/htt...,NaN,NaN,NaN,NaN,NaN
1036,12678,Chad,TCD,TD,PARTIAL,BORDER_CLOSURE,06_01_20,06_15_20,1,All,NaN,0,NaN,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://www.garda.com/crisis24/news-alerts/347...,NaN,NaN,NaN,NaN,NaN
556,NL25,Zambia,ZMB,ZM,PARTIAL,VISA_BAN,04_29_20,08_01_20,0,NaN,NaN,0,NaN,NaN,...,1,All,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20201128210043/htt...,NaN,NaN,NaN,NaN,NaN
276,141930,Finland,FIN,FI,COMPLETE,SPECIFIC_COUNTRY,11_05_20,12_13_20,0,NaN,NaN,0,NaN,NaN,...,0,NaN,NaN,1,citizens,1,"Vatican City, Australia, Japan, Rwanda, South ...",0,http://web.archive.org/web/20210119212243/http...,NaN,NaN,NaN,NaN,NaN
5,497,Namibia,NAM,NaN,COMPLETE,ESSENTIAL_ONLY,06_02_20,06_29_20,0,NaN,NaN,0,NaN,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20201205195856/htt...,NaN,NaN,NaN,NaN,NaN
1078,118674,Kuwait,KWT,KW,PARTIAL,BORDER_CLOSURE,09_28_20,NONE,0,NaN,NaN,1,Specific,Iraq border reopened,...,0,NaN,NaN,0,NaN,0,NaN,0,https://news.kuwaittimes.net/website/pcr-test-...,NaN,NaN,NaN,NaN,NaN
991,7721,Bulgaria,BGR,BG,PARTIAL,BORDER_CLOSURE,04_15_20,NONE,1,Specific,"Italy, Spain, France, the United Kingdom, Nort...",0,NaN,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20200410152223/htt...,NaN,NaN,NaN,NaN,NaN

In [4]:
# viewing current columns
policy_df.columns

Index(['ID', 'COUNTRY_NAME', 'ISO3', 'ISO2', 'POLICY_TYPE', 'POLICY_SUBTYPE',
       'START_DATE', 'END_DATE', 'AIR', 'AIR_TYPE', 'TARGETS_AIR', 'LAND',
       'LAND_TYPE', 'TARGETS_LAND', 'SEA', 'SEA_TYPE', 'TARGETS_SEA',
       'CITIZEN', 'CITIZEN_LIST', 'HISTORY_BAN', 'HISTORY_BAN_LIST', 'REFUGEE',
       'REFUGEE_LIST', 'VISA_BAN', 'VISA_BAN_TYPE', 'VISA_BAN_LIST',
       'CITIZEN_EXCEP', 'CITIZEN_EXCEP_LIST', 'COUNTRY_EXCEP',
       'COUNTRY_EXCEP_LIST', 'WORK_EXCEP', 'SOURCE0', 'SOURCE1', 'SOURCE2',
       'SOURCE3', 'SOURCE4', 'SOURCE5'],
      dtype='object')

In [5]:
# taking columns subset
policy_df = policy_df[['ID', 'COUNTRY_NAME', 'ISO3', 'POLICY_TYPE', 'POLICY_SUBTYPE',
       'START_DATE', 'AIR', 'AIR_TYPE', 'TARGETS_AIR', 'LAND',
       'LAND_TYPE', 'TARGETS_LAND', 'SEA', 'SEA_TYPE', 'TARGETS_SEA',
       'CITIZEN', 'CITIZEN_LIST', 'HISTORY_BAN', 'HISTORY_BAN_LIST', 'REFUGEE',
       'REFUGEE_LIST', 'VISA_BAN', 'VISA_BAN_TYPE', 'VISA_BAN_LIST',
       'CITIZEN_EXCEP', 'CITIZEN_EXCEP_LIST', 'COUNTRY_EXCEP',
       'COUNTRY_EXCEP_LIST', 'WORK_EXCEP']]
policy_df.columns

Index(['ID', 'COUNTRY_NAME', 'ISO3', 'POLICY_TYPE', 'POLICY_SUBTYPE',
       'START_DATE', 'AIR', 'AIR_TYPE', 'TARGETS_AIR', 'LAND', 'LAND_TYPE',
       'TARGETS_LAND', 'SEA', 'SEA_TYPE', 'TARGETS_SEA', 'CITIZEN',
       'CITIZEN_LIST', 'HISTORY_BAN', 'HISTORY_BAN_LIST', 'REFUGEE',
       'REFUGEE_LIST', 'VISA_BAN', 'VISA_BAN_TYPE', 'VISA_BAN_LIST',
       'CITIZEN_EXCEP', 'CITIZEN_EXCEP_LIST', 'COUNTRY_EXCEP',
       'COUNTRY_EXCEP_LIST', 'WORK_EXCEP'],
      dtype='object')

In [6]:
# renaming the columns
policy_df.columns = ['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Air_ban',
                             'Air_ban_type', 'Air_ban_info', 'Land_ban', 'Land_ban_type', 'Land_ban_info', 
                             'Sea_ban', 'Sea_ban_type', 'Sea_ban_info','Citizen_ban', 'Citizen_ban_info', 
                             'Travel_history_ban', 'Travel_history_ban_info', 
                             'Refugee_ban', 'Refugee_ban_info', 
                             'Visa_ban', 'Visa_ban_list', 'Visa_ban_info', 
                             'Citizen_exceptions', 'Citizen_exceptions_info', 
                             'Country_exceptions', 'Country_exceptions_info', 'Work_exceptions']
policy_df.columns

Index(['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype',
       'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info',
       'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type',
       'Sea_ban_info', 'Citizen_ban', 'Citizen_ban_info', 'Travel_history_ban',
       'Travel_history_ban_info', 'Refugee_ban', 'Refugee_ban_info',
       'Visa_ban', 'Visa_ban_list', 'Visa_ban_info', 'Citizen_exceptions',
       'Citizen_exceptions_info', 'Country_exceptions',
       'Country_exceptions_info', 'Work_exceptions'],
      dtype='object')

In [7]:
# re-viewing the columns
policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
0,118,Brunei Darussalam,BRN,COMPLETE,ESSENTIAL_ONLY,03_23_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
1,259,Morocco,MAR,COMPLETE,ESSENTIAL_ONLY,03_20_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
2,362,"Korea, Democratic People's Republic of",PRK,COMPLETE,ESSENTIAL_ONLY,01_22_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
3,386,Marshall Islands,MHL,COMPLETE,ESSENTIAL_ONLY,03_08_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
4,470,Lao People's Democratic Republic,LAO,COMPLETE,ESSENTIAL_ONLY,03_16_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0

In [8]:
# checking which cols have null values
policy_df.isnull().sum()

Policy_id                     0
Country                       0
Country_id                    0
Policy_type                   0
Policy_subtype                0
Policy_start_date             0
Air_ban                       0
Air_ban_type                891
Air_ban_info               1034
Land_ban                      0
Land_ban_type              1084
Land_ban_info              1156
Sea_ban                       0
Sea_ban_type               1211
Sea_ban_info               1242
Citizen_ban                   0
Citizen_ban_info           1209
Travel_history_ban            0
Travel_history_ban_info    1154
Refugee_ban                   0
Refugee_ban_info           1270
Visa_ban                      0
Visa_ban_list              1181
Visa_ban_info              1236
Citizen_exceptions            0
Citizen_exceptions_info     904
Country_exceptions            0
Country_exceptions_info    1101
Work_exceptions               0
dtype: int64

In [9]:
# renaming NaNs
policy_df.fillna('no policy', inplace=True)
policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
0,118,Brunei Darussalam,BRN,COMPLETE,ESSENTIAL_ONLY,03_23_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
1,259,Morocco,MAR,COMPLETE,ESSENTIAL_ONLY,03_20_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
2,362,"Korea, Democratic People's Republic of",PRK,COMPLETE,ESSENTIAL_ONLY,01_22_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
3,386,Marshall Islands,MHL,COMPLETE,ESSENTIAL_ONLY,03_08_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
4,470,Lao People's Democratic Republic,LAO,COMPLETE,ESSENTIAL_ONLY,03_16_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [10]:
# finding length of dataframe
len(policy_df)

1271

In [11]:
# finding number of countries in df
len(policy_df['Country_id'].unique())

243

In [12]:
# sorting the country id alphabetically
sorted_policy_df = policy_df.sort_values('Country_id')
sorted_policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
194,CH7,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,03_16_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents",0,no policy,0
296,CH8,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,07_10_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
84,MS50,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,03_26_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
295,CH6,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,07_01_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
81,MG12,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,03_26_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [13]:
# finding dtype for Start Date col
sorted_policy_df['Policy_start_date'].dtype

dtype('O')

In [14]:
# impossible date
sorted_policy_df[sorted_policy_df['Policy_start_date'] == '04_31_20']

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
93,NL3,Ecuador,ECU,COMPLETE,ESSENTIAL_ONLY,04_31_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [15]:
# formatting dates for use in datetime
# replacing nons and 0s with fake date 
dates_list = [x.replace('_', '-') for x in sorted_policy_df['Policy_start_date']]
dates_list_start = ['01-01-01' if x == 'NONE' or x == '0' else x for x in dates_list]
# educated guess as to end date of errant date shown in above cell
dates_list_edited = ['04-21-20' if x == '04-31-20' else x for x in dates_list_start]

In [16]:
# replacing Start Date col w/ edited dates list
sorted_policy_df['Policy_start_date'] = dates_list_edited
sorted_policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
194,CH7,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,03-16-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents",0,no policy,0
296,CH8,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,07-10-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
84,MS50,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,03-26-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
295,CH6,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,07-01-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
81,MG12,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,03-26-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [17]:
# converting Start Date col to dtype datetime
sorted_policy_df['Policy_start_date'] = pd.to_datetime(sorted_policy_df['Policy_start_date'])

In [18]:
# checking dtype
sorted_policy_df['Policy_start_date'].dtype

dtype('<M8[ns]')

In [19]:
# sorting by country id then start date
double_sorted_policy_df = sorted_policy_df.sort_values(['Country_id','Policy_start_date'])
double_sorted_policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
194,CH7,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,2020-03-16,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents",0,no policy,0
217,MS49,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,2020-03-16,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents, family members ...",0,no policy,0
209,MG0,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,2020-03-17,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,residents,0,no policy,0
84,MS50,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,2020-03-26,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
81,MG12,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,2020-03-26,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [20]:
# keeping only the rows with the most recent date for each country
last_date_df = double_sorted_policy_df.drop_duplicates(subset='Country_id', keep='last')
last_date_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
296,CH8,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,2020-07-10,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
1017,11020,Afghanistan,AFG,PARTIAL,BORDER_CLOSURE,2020-03-24,1,Specific,all commercial flights suspended except for so...,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
1252,SN63,Angola,AGO,PARTIAL,BORDER_CLOSURE,2020-10-19,1,Specific,"Afghanistan, Aland Islands, Albania, Algeria, ...",1,All,no policy,1,All,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
299,CK4,Anguilla,AIA,COMPLETE,SPECIFIC_COUNTRY,2020-07-12,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, residents",1,"Aruba, Bonaire, St Eustatius and Saba, Belize,...",0
423,EB65,Ã…land Islands,ALA,COMPLETE,WORK_EXCEP,2020-11-19,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"nationals of Finland, family members of nation...",1,"Vactican City, Australia, South Korea, Japan, ...",1

In [21]:
# len of df
len(last_date_df)

243

In [22]:
# showing cols of df
last_date_df.columns

Index(['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype',
       'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info',
       'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type',
       'Sea_ban_info', 'Citizen_ban', 'Citizen_ban_info', 'Travel_history_ban',
       'Travel_history_ban_info', 'Refugee_ban', 'Refugee_ban_info',
       'Visa_ban', 'Visa_ban_list', 'Visa_ban_info', 'Citizen_exceptions',
       'Citizen_exceptions_info', 'Country_exceptions',
       'Country_exceptions_info', 'Work_exceptions'],
      dtype='object')

In [23]:
# creating a policy id and country id junction table
id_junction_df = last_date_df[['Policy_id', 'Country_id']].reset_index(drop=True).sort_values('Country_id')
id_junction_df.head()

  Policy_id Country_id
0       CH8        ABW
1     11020        AFG
2      SN63        AGO
3       CK4        AIA
4      EB65        ALA

In [24]:
# separating out only rows where a complete ban was in effect, saving only cols that apply
full_closures_df = last_date_df[last_date_df['Policy_type'] == 'COMPLETE'][['Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 
                                                                            'Policy_start_date', 'Citizen_exceptions', 'Citizen_exceptions_info', 
                                                                            'Country_exceptions','Country_exceptions_info', 'Work_exceptions']]
full_closures_df.reset_index(inplace=True, drop=True)

# exporting full closure table to csv
full_closures_df.to_csv('Clean/full_closures_table.csv', index=False)
full_closures_df.head()

,Policy_id,Country_id,Policy_type,Policy_subtype,Policy_start_date,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
0,CH8,ABW,COMPLETE,SPECIFIC_COUNTRY,2020-07-10,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
1,CK4,AIA,COMPLETE,SPECIFIC_COUNTRY,2020-07-12,1,"citizens, residents",1,"Aruba, Bonaire, St Eustatius and Saba, Belize,...",0
2,EB65,ALA,COMPLETE,WORK_EXCEP,2020-11-19,1,"nationals of Finland, family members of nation...",1,"Vactican City, Australia, South Korea, Japan, ...",1
3,NL75,ASM,COMPLETE,CITIZEN_EXCEP,2020-12-01,1,citizens,0,no policy,0
4,EB18,ATG,COMPLETE,SPECIFIC_COUNTRY,2020-04-23,0,no policy,1,Dominican Republic,0

In [25]:
# separating out only rows where a partial ban was in effect, saving only cols that apply
partial_closures_df = last_date_df[last_date_df['Policy_type'] == 'PARTIAL'][['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype',
       'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info',
       'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type',
       'Sea_ban_info', 'Citizen_ban', 'Citizen_ban_info', 'Travel_history_ban',
       'Travel_history_ban_info', 'Refugee_ban', 'Refugee_ban_info',
       'Visa_ban', 'Visa_ban_list', 'Visa_ban_info']]
partial_closures_df.reset_index(inplace=True, drop=True)
partial_closures_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,Sea_ban_info,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info
0,11020,Afghanistan,AFG,PARTIAL,BORDER_CLOSURE,2020-03-24,1,Specific,all commercial flights suspended except for so...,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy
1,SN63,Angola,AGO,PARTIAL,BORDER_CLOSURE,2020-10-19,1,Specific,"Afghanistan, Aland Islands, Albania, Algeria, ...",1,All,no policy,1,All,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy
2,1940,Albania,ALB,PARTIAL,BORDER_CLOSURE,2020-03-24,0,no policy,no policy,0,no policy,no policy,1,Specific,All ferries to/from Italy & other red areas ar...,0,no policy,0,no policy,0,no policy,0,no policy,no policy
3,5314,United Arab Emirates,ARE,PARTIAL,VISA_BAN,2020-04-03,0,no policy,no policy,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,1,specific,New visa seekers and existing valid visa holders
4,140705,Argentina,ARG,PARTIAL,BORDER_CLOSURE,2020-11-01,1,Specific,Only citizens allowed to fly,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy

In [26]:
# partial closure -- border closure
# by this point refugee bans are no longer in the dataframe (bans have ended by that time point) 
partial_borders_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'BORDER_CLOSURE'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info', 
        'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type', 'Sea_ban_info']]
)

# partial closure -- visa ban
partial_visa_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'VISA_BAN'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Visa_ban_list', 'Visa_ban_info']]
).reset_index(drop=True)


# partial closure -- citizenship ban
partial_citizenship_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'CITIZENSHIP_BAN'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Citizen_ban_info']]
).reset_index(drop=True)


# partial closure -- history ban
partial_history_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'HISTORY_BAN'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Travel_history_ban_info']]
).reset_index(drop=True)

# exporting partial closure tables to csv
partial_borders_df.to_csv('Clean/partial_borders_table.csv', index=False)
partial_visa_df.to_csv('Clean/partial_visa_table.csv', index=False)
partial_citizenship_df.to_csv('Clean/partial_citizenship_table.csv', index=False)
partial_history_df.to_csv('Clean/partial_history_table.csv', index=False)

In [27]:
# separating out only rows where no ban was in effect, saving only cols that apply
no_closures_df = last_date_df[last_date_df['Policy_type'] == 'NOPOLICYIMPLEMENTED'][['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype']]
no_closures_df.reset_index(inplace=True, drop=True)

no_closures_df.to_csv('Clean/no_closures_table.csv', index=False)
no_closures_df.head()

  Policy_id     Country Country_id          Policy_type Policy_subtype
0      EB45     Andorra        AND  NOPOLICYIMPLEMENTED           NONE
1      EB10  Antarctica        ATA  NOPOLICYIMPLEMENTED           NONE
2      MS82    Guernsey        GGY  NOPOLICYIMPLEMENTED           NONE
3      MS40        Guam        GUM  NOPOLICYIMPLEMENTED           NONE
4      MS81      Jersey        JEY  NOPOLICYIMPLEMENTED           NONE

In [28]:
# checking lengths of the 3 dfs
len(full_closures_df), len(partial_closures_df), len(no_closures_df)

(108, 127, 8)

In [29]:
# creation of policy table
# lists of policy types, subtypes and ids
full_policy_subtypes_list = [x for x in full_closures_df['Policy_subtype'].unique()]
full_policy_types_list = ['Full' for x in full_closures_df['Policy_subtype'].unique()]
full_policy_type_ids_list = [f'F{x}' for x in range(1, len(full_policy_types_list)+1)]

partial_policy_subtypes_list = [x for x in partial_closures_df['Policy_subtype'].unique()]
partial_policy_types_list = ['Partial' for x in partial_closures_df['Policy_subtype'].unique()]
partial_policy_type_ids_list = [f'P{x}' for x in range(1, len(partial_policy_types_list)+1)]

no_policy_subtypes_list = [x for x in no_closures_df['Policy_subtype'].unique()]
no_policy_types_list = ['None' for x in no_closures_df['Policy_subtype'].unique()]
no_policy_type_ids_list = [f'N{x}' for x in range(1, len(no_policy_types_list)+1)]

all_policy_subtypes_list = full_policy_subtypes_list + partial_policy_subtypes_list + no_policy_subtypes_list
all_policy_types_list = full_policy_types_list + partial_policy_types_list + no_policy_types_list
policy_type_id_list = full_policy_type_ids_list + partial_policy_type_ids_list + no_policy_type_ids_list
all_policy_types_list, all_policy_subtypes_list, policy_type_id_list

(['Full',
  'Full',
  'Full',
  'Full',
  'Partial',
  'Partial',
  'Partial',
  'Partial',
  'None'],
 ['SPECIFIC_COUNTRY',
  'WORK_EXCEP',
  'CITIZEN_EXCEP',
  'ESSENTIAL_ONLY',
  'BORDER_CLOSURE',
  'VISA_BAN',
  'CITIZENSHIP_BAN',
  'HISTORY_BAN',
  'NONE'],
 ['F1', 'F2', 'F3', 'F4', 'P1', 'P2', 'P3', 'P4', 'N1'])

In [30]:
# creation of policy table
# creating df out of lists
policy_types_df = pd.DataFrame({
    'Policy_type_id': policy_type_id_list, 'Policy_type': all_policy_types_list, 'Policy_subtype': all_policy_subtypes_list})
policy_types_df

  Policy_type_id Policy_type    Policy_subtype
0             F1        Full  SPECIFIC_COUNTRY
1             F2        Full        WORK_EXCEP
2             F3        Full     CITIZEN_EXCEP
3             F4        Full    ESSENTIAL_ONLY
4             P1     Partial    BORDER_CLOSURE
5             P2     Partial          VISA_BAN
6             P3     Partial   CITIZENSHIP_BAN
7             P4     Partial       HISTORY_BAN
8             N1        None              NONE

In [31]:
# full closures -- country exceptions
full_country_df = pd.DataFrame(
    full_closures_df[full_closures_df['Country_exceptions'] == 1][['Policy_id', 'Policy_start_date', 'Country_exceptions_info']].reset_index(drop=True)
)
full_country_df['Policy_type_id'] = 'F1'

# full closures -- work exceptions --! no further info on this closure type (no info col)
full_work_df = pd.DataFrame(
    full_closures_df[full_closures_df['Work_exceptions'] == 1][['Policy_id', 'Policy_start_date']].reset_index(drop=True)
)
full_work_df['Policy_type_id'] = 'F2'

# full closures -- citizen exceptions
full_citizens_df = pd.DataFrame(
    full_closures_df[full_closures_df['Citizen_exceptions'] == 1][['Policy_id', 'Policy_start_date', 'Citizen_exceptions_info']].reset_index(drop=True)
)
full_citizens_df['Policy_type_id'] = 'F3'

# full closures -- essential only --! no further info on this closure type (no info col)
full_essential_df = pd.DataFrame(
    full_closures_df[full_closures_df['Policy_subtype'] == 'ESSENTIAL_ONLY'][['Policy_id', 'Policy_start_date']].reset_index(drop=True)
)
full_essential_df['Policy_type_id'] = 'F4'

full_citizens_df.head()

,Policy_id,Policy_start_date,Citizen_exceptions_info,Policy_type_id
0,CH8,2020-07-10,"residents with prior authorization, non-reside...",F3
1,CK4,2020-07-12,"citizens, residents",F3
2,EB65,2020-11-19,"nationals of Finland, family members of nation...",F3
3,NL75,2020-12-01,citizens,F3
4,138822,2020-10-16,"Australian Citizens, permanent residents in Au...",F3

In [32]:
# partial closure -- border closure
# by this point refugee bans are no longer in the dataframe (bans have ended by that time point) 
# split further into air, land, sea
partial_borders_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'BORDER_CLOSURE'][[
        'Policy_id', 'Country_id', 'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info', 
        'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type', 'Sea_ban_info']]
)
partial_borders_df['Policy_type_id'] = 'P1'

# # partial -- air
partial_air_df = pd.DataFrame(partial_borders_df[partial_borders_df['Air_ban'] == 1][[
    'Policy_id', 'Policy_start_date', 'Air_ban_type', 'Air_ban_info', 'Policy_type_id']]).reset_index(drop=True)
air_ban_info_list = ['no further specifications' if x == 'no policy' else x for x in partial_air_df['Air_ban_info']]
partial_air_df['Air_ban_info'] = air_ban_info_list

# # partial -- sea
partial_sea_df = pd.DataFrame(partial_borders_df[partial_borders_df['Sea_ban'] == 1][[
    'Policy_id', 'Policy_start_date', 'Sea_ban_type', 'Sea_ban_info', 'Policy_type_id']]).reset_index(drop=True)
sea_ban_info_list = ['no further specifications' if x == 'no policy' else x for x in partial_sea_df['Sea_ban_info']]
partial_sea_df['Sea_ban_info'] = sea_ban_info_list

# # partial -- land
partial_land_df = pd.DataFrame(partial_borders_df[partial_borders_df['Land_ban'] == 1][[
    'Policy_id', 'Policy_start_date', 'Land_ban_type', 'Land_ban_info', 'Policy_type_id']]).reset_index(drop=True)
land_ban_info_list = ['no further specifications' if x == 'no policy' else x for x in partial_land_df['Land_ban_info']]
partial_land_df['Land_ban_info'] = land_ban_info_list

# partial closure -- visa ban
partial_visa_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'VISA_BAN'][[
        'Policy_id', 'Policy_start_date', 'Visa_ban_list', 'Visa_ban_info']]
).reset_index(drop=True)
partial_visa_df['Policy_type_id'] = 'P2'

# partial closure -- citizenship ban
partial_citizenship_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'CITIZENSHIP_BAN'][[
        'Policy_id', 'Policy_start_date', 'Citizen_ban_info']]
).reset_index(drop=True)
partial_citizenship_df['Policy_type_id'] = 'P3'

# partial closure -- history ban
partial_history_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'HISTORY_BAN'][[
        'Policy_id', 'Policy_start_date', 'Travel_history_ban_info']]
).reset_index(drop=True)
partial_history_df['Policy_type_id'] = 'P4'

partial_air_df.sample(5)

,Policy_id,Policy_start_date,Air_ban_type,Air_ban_info,Policy_type_id
66,MS22,2020-03-24,All,no further specifications,P1
0,11020,2020-03-24,Specific,all commercial flights suspended except for so...,P1
63,16402,2020-08-10,All,no further specifications,P1
34,EB93,2020-12-23,Specific,United Kingdom,P1
45,WY4,2020-10-03,All,"Australia, Singapore, Hong Kong, Japan, Solomo...",P1

In [33]:
# no closures, adding the policy type
no_closures_df['Policy_type_id'] = 'N1'
no_closures_df = no_closures_df[['Policy_id', 'Policy_type_id']]
no_closures_df.head()

  Policy_id Policy_type_id
0      EB45             N1
1      EB10             N1
2      MS82             N1
3      MS40             N1
4      MS81             N1

In [34]:
# reading in csvs
vaccinations_df = pd.read_csv('Clean/vaccinations_cleaned.csv')
travel_df = pd.read_csv('Clean/travel_restrictions_clean.csv')

In [35]:
# removing newline breaks and breaks
travel_df['Quarantine_type'] = travel_df['Quarantine_type'].replace('\\n',' ', regex=True)
travel_df['Quarantine_type'] = travel_df['Quarantine_type'].replace('<br>',' ', regex=True)

In [36]:
# re-viewing travel_df
travel_df.head()

,Country,Country_id,Quarantine_type,Quarantine_start_date
0,Kiribati,KIR,Quarantine requirement outside territory. Kiri...,2020-06-28
1,Kosovo,RKS,Self-isolation at own accommodation- subject t...,2021-01-21
2,Kuwait,KWT,Self-isolation at own accommodation. On entry...,2021-05-02
3,Kyrgyzstan,KGZ,Quarantine requirement at government designate...,2021-01-02
4,Lao People's Democratic Republic,LAO,Quarantine requirement at government designate...,2021-04-02

In [37]:
# number of countries in each df - travel restrictions has the most
len(vaccinations_df['Country'].unique()), len(travel_df['Country'].unique()), len(last_date_df['Country'].unique())

(58, 267, 243)

In [38]:
# creating a countries names and ids table
# subsetting each CSV source df for only country names and IDs
vacc_countries_df = vaccinations_df[['Country', 'Country_id']]
immig_countries_df = last_date_df[['Country', 'Country_id']]
travel_countries_df = travel_df[['Country', 'Country_id']]

# outer merging the travel restrictions and immigration restriction dfs 
# to capture country names not in the other table
first_countries_merge = travel_countries_df.merge(immig_countries_df, how='outer', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
print(len(first_countries_merge))

# outer merging the vaccinations and first merge dfs
# to capture country names not in the other table
full_merge = first_countries_merge.merge(vacc_countries_df, how='outer', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
print(len(full_merge))
full_merge.head()

270
271

                            Country Country_id
0                          Kiribati        KIR
1                            Kosovo        RKS
2                            Kuwait        KWT
3                        Kyrgyzstan        KGZ
4  Lao People's Democratic Republic        LAO

In [39]:
# checking to see if there are any duplicates in the merged tables -- there aren't
full_merge[full_merge.duplicated() == True]

Empty DataFrame
Columns: [Country, Country_id]
Index: []

In [40]:
# making the table alphabetical, resetting the index, saving to a new descriptive name
countries_names_ids_df = full_merge.sort_values('Country').reset_index(drop=True)
countries_names_ids_df.head()
# exporting country table to csv
countries_names_ids_df.to_csv('Clean/country.csv', index=False)

In [41]:
# doing first merge w/ each of the 3 closure dfs, w/ the travel restrictions df
full_closures_merged = full_closures_df.merge(travel_df, how='inner', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country')
full_closures_merged.head()

,Policy_id,Country_id,Policy_type,Policy_subtype,Policy_start_date,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions,Quarantine_type,Quarantine_start_date
0,CH8,ABW,COMPLETE,SPECIFIC_COUNTRY,2020-07-10,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0,Self-isolation at own accommodation- subject t...,2020-12-17
1,CK4,AIA,COMPLETE,SPECIFIC_COUNTRY,2020-07-12,1,"citizens, residents",1,"Aruba, Bonaire, St Eustatius and Saba, Belize,...",0,Quarantine at government designated site or Go...,2021-03-02
2,EB65,ALA,COMPLETE,WORK_EXCEP,2020-11-19,1,"nationals of Finland, family members of nation...",1,"Vactican City, Australia, South Korea, Japan, ...",1,Unknown,2001-01-01
3,NL75,ASM,COMPLETE,CITIZEN_EXCEP,2020-12-01,1,citizens,0,no policy,0,Quarantine Requirement outside territory. C...,2020-07-29
4,EB18,ATG,COMPLETE,SPECIFIC_COUNTRY,2020-04-23,0,no policy,1,Dominican Republic,0,Quarantine requirement at government designate...,2021-09-02

In [42]:
# doing first merge w/ each of the 3 closure dfs, w/ the travel restrictions df
partial_closures_merged = partial_closures_df.merge(travel_df, how='inner', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
partial_closures_merged.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,Sea_ban_info,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Quarantine_type,Quarantine_start_date
0,11020,Afghanistan,AFG,PARTIAL,BORDER_CLOSURE,2020-03-24,1,Specific,all commercial flights suspended except for so...,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy,No declared requirements. There are currentl...,2021-01-29
1,SN63,Angola,AGO,PARTIAL,BORDER_CLOSURE,2020-10-19,1,Specific,"Afghanistan, Aland Islands, Albania, Algeria, ...",1,All,no policy,1,All,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy,Quarantine requirement at government designate...,2020-04-02
2,1940,Albania,ALB,PARTIAL,BORDER_CLOSURE,2020-03-24,0,no policy,no policy,0,no policy,no policy,1,Specific,All ferries to/from Italy & other red areas ar...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,Self Isolation- subject to origin. There wil...,2021-01-14
3,5314,United Arab Emirates,ARE,PARTIAL,VISA_BAN,2020-04-03,0,no policy,no policy,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,1,specific,New visa seekers and existing valid visa holders,Self-isolation at own accommodation. Stringen...,2021-11-02
4,140705,Argentina,ARG,PARTIAL,BORDER_CLOSURE,2020-11-01,1,Specific,Only citizens allowed to fly,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy,Self-isolation at own accommodation. All trav...,2021-10-02

In [43]:
# doing first merge w/ each of the 3 closure dfs, w/ the travel restrictions df
#no_closures_merged = no_closures_df.merge(travel_df, how='inner', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
#no_closures_merged.head()

In [44]:
# doing second merge w/ each of the 3 closure dfs, with vaccination data
# full_closures_all = full_closures_df.merge(vaccinations_df, how='left', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
# full_closures_all.sample(5)

In [45]:
# doing second merge w/ each of the 3 closure dfs, with vaccination data
# partial_closures_all = partial_closures_df.merge(vaccinations_df, how='left', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
# partial_closures_all.sample(5)

In [46]:
# doing second merge w/ each of the 3 closure dfs, with vaccination data
# no_closures_all = no_closures_df.merge(vaccinations_df, how='left', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP')
# no_closures_all.head(10)

In [47]:
# checking which cols have null values
# replacing nulls (only in vaccination sourced data cols) with 'no information'
# re-checking null values - none left
# print(full_closures_all.isnull().sum(), partial_closures_all.isnull().sum(), no_closures_all.isnull().sum())
# full_closures_all.fillna('no information', inplace=True)
# partial_closures_all.fillna('no information', inplace=True)
# no_closures_all.fillna('no information', inplace=True)
# full_closures_all.isnull().sum(), partial_closures_all.isnull().sum(), no_closures_all.isnull().sum()

In [48]:
# replacing the now 'no information' dates with placeholder date '01-01-01' in case datetimes need to be applied
# creating lists to hold the dates
# replacing the date cols with those lists
# full_closures_dates = ['01-01-01' if x == 'no information' else x for x in full_closures_all['vaccination_date']]
# partial_closures_dates = ['01-01-01' if x == 'no information' else x for x in partial_closures_all['vaccination_date']]
# no_closures_dates = ['01-01-01' if x == 'no information' else x for x in no_closures_all['vaccination_date']]

# full_closures_all['vaccination_date'] = full_closures_dates
# partial_closures_all['vaccination_date'] = partial_closures_dates
# no_closures_all['vaccination_date'] = no_closures_dates

In [49]:
# exporting all policies df to csv
#last_date_df.to_csv('Clean/policy_cleaned.csv', index=False)

In [50]:
# exporting policy level specific dfs to csvs
#full_closures_all.to_csv('Clean/full_closures_df', index=False)
#partial_closures_all.to_csv('Clean/partial_closures_df', index=False)
#no_closures_all.to_csv('Clean/no_closures_df', index=False)